### PR TITLE
RFC: syntax update

### PR DESCRIPTION
**Pull request by felixrehren**
* Syntax updating for compatibility with 0.6.0-dev
    * replaced `KVPair{K,V}` type with standard `Pair{K,V}`
* changed `factcheck` to `@test` usage

Almost compatible with 0.5.0, except some problems marked in the test suite. Not sure what to do here:

    julia> PersistentSet(Integer[1,2,3])
    ERROR: MethodError: Cannot `convert` an object of type Pair{Int64,Void} to an object of type Pair{Integer,Void}

or here:

    julia> append(vec(1:31), 32) == vec(1:32)
    true
    julia> @test append(vec(1:31), 32) == vec(1:32)
    [...] ERROR: MethodError: no method matching unsafe_length(::Int64)

### CODE REVIEW

**Comment by felixrehren** [comment]
Travis passes for `nightly`, runs into the above errors for `0.5.0`, and fails on `0.4.0` because `@testset` is not defined there

**Comment by felixrehren** [comment]
Would love help making this functional. Ping @shashi as the last person to commit here

I can unwind parts of this PR if too aggressive?

**Comment by tkelman** [comment]
You could either depend on BaseTestNext on 0.4, or bump the minimum Julia version to 0.5.

**Comment by felixrehren** [comment]
Thanks @tkelman. I took the easy way out, avoiding the tests mentioned above that were breaking `v"0.5"`. Hope build is successful now ...

**Comment by shashi** [comment]
Thanks @felixrehren! This is a great improvement.

**Comment by tkelman** [comment]
Since this is almost a complete rewrite, you should probably double-check that it won't break Arbiter or Patchwork, its reverse-dependencies.

**Comment by shashi** [comment]
Not much has been rewritten, but code has been moved around. Just ran tests for Patchwork and Arbiter on 0.5 - all green.

**Pull request merged**
