### PR TITLE
Julia 0.4 compat.

### PR DESCRIPTION
**Pull request by dcjones**
Fixes Julia 0.4 compatibility.

### CODE REVIEW

**Comment by kmsquire** [comment]
Passes for me on v0.3 and v0.4.  Perhaps someone with admin access can flip the switch on travis to enable testing?  Cc: @StefanKarpinski @ViralBShah

**Comment by StefanKarpinski** [comment]
I think I've turned this on now. How do we check?

**Comment by shashi** [comment]
The next commit should trigger a Travis build and we'll know by looking at the badge in the README.

**Comment by shashi** [comment]
Well it didn't :/

**Comment by kmsquire** [comment]
@StefanKarpinski (or whomever gets to this), the feature should be turned on at https://travis-ci.org/profile/JuliaLang

**Comment by shashi** [comment]
Just had Viral turn off and turn on the travis builds. Working now. :+1:

**Pull request merged**
